package APIServer;

import java.io.IOException;
import java.util.Properties;
import java.util.UUID;
import org.restlet.Request;
import org.restlet.data.Form;
import org.restlet.data.MediaType;
import org.restlet.representation.FileRepresentation;
import org.restlet.resource.Get;
import org.restlet.resource.ServerResource;

/**
 * Return wave files generated by calling festival in Terminal.
 * We put all the wave files into folder GeneratedWave
 * the file will be deleted after having been sent to the client
 */

public class Text2Wave extends ServerResource{
	String txt = "";
	String errorWave = "../WaveSource/Error.wav";
	String wavePath = "";
	String festivalHome = "";
	
	private void getProperties(){
		Properties configFile = new Properties();
		try {
			configFile.load(getClass().getResourceAsStream("config.properties"));
			wavePath = configFile.getProperty("waveFilePath");
			festivalHome = configFile.getProperty("festivalHome");
		} catch (IOException e) {
	
			e.printStackTrace();
		}
	}
	
	@Get
    public FileRepresentation getResource() {
		getProperties();
		FileRepresentation result = null;
		Request request = getRequest();
		Form form = request.getResourceRef().getQueryAsForm();
		txt = form.getValues("txt");	
		result = Process(txt);	
		return result;
    }

	private FileRepresentation Process(String txt){		
		FileRepresentation result = new FileRepresentation(errorWave,MediaType.AUDIO_WAV);
		String waveFilePath = "";
		String txtFile = GenerateTxtFile(txt);		
		waveFilePath = wavePath + GenerateUid() + ".wav";
		String command = festivalHome + "text2wave " + txtFile + " -o "  + waveFilePath;
		if(ExcuteCommand(command))
		{
			result = new FileRepresentation(waveFilePath,MediaType.AUDIO_WAV);			
		}
		return result;
	}
	
	private String GenerateUid()
	{
		return UUID.randomUUID().toString();
	}
	
	private String GenerateTxtFile(String txt)
	{
		String fileName = "";
		String command = "";
		String uniqueID = GenerateUid();
		fileName = wavePath + uniqueID + ".txt";
		command = "echo " + "'" + txt + "'" + " > " + fileName;
		String[] commandLine = {"sh", "-c", command};
		if(ExcuteCommand(commandLine))
		{
			return fileName;
		}
		else 
		{
			return "";
		}
	}
	
	private boolean ExcuteCommand(String[] command) 
	{
		boolean result = false;
		Process p;
		try {
			p = Runtime.getRuntime().exec(command);
			p.waitFor();
			result = true;
		} catch (Exception e) {
			e.printStackTrace();
		}		
		return result;
	}
	
	private boolean ExcuteCommand(String command) 
	{
		boolean result = false;
		Process p;
		try {
			p = Runtime.getRuntime().exec(command);
			p.waitFor();
			result = true;
		} catch (Exception e) {
			e.printStackTrace();
		}		
		return result;
	}
}
